services:
  movie-review-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"    # FastAPI服务
      - "8501:8501"    # Streamlit界面
    environment:
      - KIMI_API_KEY=${KIMI_API_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - API_BASE_URL=http://localhost:8000
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      - ./static:/app/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - movie-review-network

networks:
  movie-review-network:
    driver: bridge